export const types = {
    //Auth Actions//
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    //Registration
    REGISTER_USER_START: "REGISTER_USER_START",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
}