export const types = {
    //Auth Actions//
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    //Registration
    REGISTER_USER_START: "REGISTER_USER_START",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
    //Mothers Actions//
    GET_MOTHERS_START: "GET_MOTHERS_START",
    GET_MOTHERS_SUCCESS: "GET_MOTHERS_SUCCESS",
    GET_MOTHERS_FAILURE: "GET_MOTHERS_FAILURE",
    //Drivers Actions//
    GET_DRIVERS_START: "GET_DRIVERS_START",
    GET_DRIVERS_SUCCESS: "GET_DRIVERS_SUCCESS",
    GET_DRIVERS_FAILURE: "GET_DRIVERS_FAILURE",
    //logout types
    LOGOUT: "LOGOUT",
};